---
title: "Keynote Presentations"
description: |
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
---

## Petya Grady &nbsp; [`r fontawesome::fa("linkedin")`](https://www.linkedin.com/in/petyagrady/)
#### Innovation Manager, ServiceMaster/Terminix & Co-Founder of CodeCrew 

Petya joined ServiceMaster (now Terminix) in 2016 where she is responsible for driving organizational alignment on innovation initiatives. She’s a founding member of the ServiceMaster Innovation Council and has been instrumental in establishing ServiceMaster’s innovation strategy and its tactical implementation. Prior to ServiceMaster, Petya was with Lokion Interactive where she worked on customer experience strategy and user experience design for clients such as American Home Shield, FedEx, Hilton, Smith & Nephew and St. Jude Children’s Cancer Research Hospital. Petya’s background and experience allow her to bring an international perspective into her work. A native of Bulgaria, she began her career as a Project Manager in the Sofia offices of Dynamo Software (previously, Netage Solutions) where she led teams to successfully implement multi-lingual projects for an array of international clients.

As an immigrant and a woman working in tech, Petya is a passionate advocate for promoting diversity and empathy in the tech industry and beyond. She is co-founder and current Board Chair of CodeCrew, a non-profit organization providing computer science training to under-represented kids in Memphis, where she focuses on organizational development, fundraising and finance. In 2015, Petya was recognized as Top 40 Under 40 by the Memphis Business Journal. In 2016, she was the first recipient of the State Farm Exist to Assist Community Service Award after being nominated by the Memphis Grizzlies Foundation.
 
Petya holds a B.A. from Sewanee: The University of the South and an M.A from Penn State University. She lives in Memphis with her husband and daughter.  

- Talk: Wednesday, June 9th at 1 p.m.
- [Recording of presentation](https://sewanee-edu.zoom.us/rec/share/s1-pJlZd2buMbu7ztOEh_auzlIxJMQelyZW76X8O-KPXBgQFkHPuxKPsMGI-Zk5K.NRZRS574htqOzFz9?startTime=1623261337000)

## Elizabeth Ann Stringer &nbsp; [`r fontawesome::fa("linkedin")`](http://www.linkedin.com/in/Elizabeth-Ann-Stringer)

Elizabeth Ann Stringer is the Chief Scientific Officer of Nashville Biosciences (NashBio), a for-profit subsidiary of the Vanderbilt University Medical Center (VUMC). NashBio is a unique data and analytics-driven biotech company that partners with pharmaceutical, diagnostics and other life sciences companies to drive the discovery and development of new therapeutics and diagnostics by leveraging VUMC’s unparalleled genomic and bioinformatics resources. Elizabeth Ann oversees client partnerships and leads NashBio’s scientific and clinical teams on successful project execution.

Prior to joining NashBio, Elizabeth Ann was the Chief Science & Clinical Officer of axialHealthcare, a health care startup combating the opioid epidemic by identifying patients at risk for poor pain medicine outcomes and outreaching to providers who care for them. As a founding member of axialHeathcare, she helped build and grow the company to $20M in revenue, serving as the subject matter expert in capital raising, business development and industry conferences. 

Elizabeth Ann holds a BS in Physics from The University of the South (Sewanee) and a PhD in Neuroimaging & Neuroscience from Vanderbilt University. She completed her postdoctoral fellowship in Pain Management at Stanford University where she studied the effects of opioids on the human brain and the intersection of pain & immunology. Elizabeth Ann has always enjoyed making sense of data and using it to tell a story & inform action. She currently resides in Nashville with her partner Sam, an artist & musician.

- Talk: Friday, June 11th at 1 p.m. in Spencer 172
- [Recording of presentation](https://sewanee-edu.zoom.us/rec/share/dJm-Dpy6Wc9QvHEpWVZ0ypt8frLyKkgWOFXDv33scQ67trEcEa1kpd9UrX4mgdcm.ixh_AU9rg1hpn0w2?startTime=1623434231000)

## Jurnell Cockhren &nbsp; [`r fontawesome::fa("linkedin")`](https://www.linkedin.com/in/jurnellcockhren/)

Jurnell Cockhren moved to Nashville after graduating from Sewanee with a B.S. in Mathematics & Physics in 2007. Jurnell's experience combines his Neuroscience, Physics, and Astronomy contributions with his passion for writing software. While working at the Vanderbilt Vision Research Center, he developed a talent for writing software to help researchers further understand the human visual system. His contributions landed in journals like 'Attention, Perception, & Psychophysics' and 'Child Psychology and Psychiatry.' In 2018, one article received the 'Clifford T. Morgan' award for Best Article from the Psychonomic Society.

Learning how to manage sizable networks in the cloud at Atiba Inc and Concert Genetics Inc helped him in his entrepreneurial pursuits. He founded Civic Hacker, LLC, a for-profit Benefit-Company that researches technology's influence on improving the lived experiences of vulnerable communities. Jurnell advises organizations that seek to make a positive social impact and allyship with vulnerable communities. He enjoys assisting groups like The Kauffman Foundation and the STEAM Advisory Board for Metropolitan Nashville Public Schools. Affiliations include The Black Codes, Python Software Foundation, and Code for Nashville. Additionally, Jurnell is a cofounder of Black In Tech Nashville.

- Talk: Wednesday, June 16th at 2:30 p.m. in Spencer 172
- Recording of presentation will be available later!

## Rayid Ghani

Bio will be here soon!

## Deirdre Mulligan

Bio will be here soon!

