---
title: "Training resources"
description: |
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

## Main curriculum

- [DataBOOM](http://www.datascience.pizza/)

## Zoom recordings

### Week 1

  - [Monday morning, 6/7/21](https://sewanee-edu.zoom.us/rec/share/4duWw4RS4XQgEPojdWV4ZBYf4yj5I6itEjoBQUJPiETL5_F9Ycy45bIYqm0TZFIh.JvWdOs-coArve9xc) : opening remarks (Jim Peterman, Joe Brew); getting started with data science and visualization
  - [Monday afternoon, 6/7/21](https://sewanee-edu.zoom.us/rec/share/fCr9YKlRcTLZXFahgOBmeXcf4ITQ01E0WnPdawzd2dF-i9lp8CF0DQDZE2N2QOIg.fi8mmVJSKT4PREM1) : introduction to [R](https://cran.r-project.org/), [RStudio](https://www.rstudio.com/), and R scripts
  - [Tuesday morning, 6/8/21](https://sewanee-edu.zoom.us/rec/share/E-nWurvcCcTm5AMXgWpMFIsl4LKeQl7rSmA19-6b5URpOEIvKT2mXtbR2VnWb051.J21rNa681l67X9V8) : practice with scripts, data structures, and built-in functions
  - [Tuesday afternoon, 6/8/21](https://sewanee-edu.zoom.us/rec/share/9yOB5Bci1kGo2yoHi4-5YjHRVosIuR53TjQYClaW_Y6ASHelttQuYZqqqiKLv1C3.768w5x1ZUJgs0MJd) : working with vectors, built-in functions, `NA`s, and `meh`s
  - [Wednesday morning, 6/9/21](https://sewanee-edu.zoom.us/rec/share/xLhGumXryEqDQQReK2Ad7yv-nuze9tZrPY1Ah3ToGuEy3S3FGCmHKvak9cicpi3V.YtmpxY6DIh1Tbjc6?startTime=1623247053000) : working with packages and `data.frame`s
  - [Wednesday afternoon, 6/9/21](https://sewanee-edu.zoom.us/rec/share/s1-pJlZd2buMbu7ztOEh_auzlIxJMQelyZW76X8O-KPXBgQFkHPuxKPsMGI-Zk5K.NRZRS574htqOzFz9?startTime=1623267257000) : `data.frame`s, piping with `%>%`, and `dplyr` magic
  - [Thursday morning, 6/10/21](https://sewanee-edu.zoom.us/rec/share/dvCRD6FWirGw8-qh6HSgWG07Kb1bUdFpWaBuDeNjBwnw4Il_q3WNxnrW57zN_pil.NzCivuI_21wrvnnM) : More with `data.frame`s and `dplyr` magic
  - [Thursday afternoon, 6/10/21](https://sewanee-edu.zoom.us/rec/share/hzSTtWZeK1FCMe9la0uDBOXzpVnnV5gqkeWF5bXFR31dOqP4gZIfMCx0I13SEToG.-KwqTQHQ--pETKAX) : Presentation by Deb McGrath on carbon sequestration work in Haiti; the Belmont principles and data ethics
  - [Friday morning, 6/11/21](https://sewanee-edu.zoom.us/rec/share/WfExudcKWW0__daU04RwYdR725rhwU4HTkyVZoi26_AkwuGqxt19OD27ND_kx1AX.KenziwbqM7yKpf8Q) : more on data ethics, working with `dplyr`
  
### Week 2

  - [Monday morning, 6/14/21](https://sewanee-edu.zoom.us/rec/share/NTqs8kLxJ5sRNjejGnlPIPrYNmSP6s2sqGVqoCZiC_EuSO0ZkYE8JfKe-Ni5FyT_.GLznNa6wsZxWCdQE) : group work
  - [Monday afternoon, 6/14/21](https://sewanee-edu.zoom.us/rec/share/UyCSrx-U9WRownUYtFZ1FjqdWyiyS7b_YMZBwGRLlawcHmdHJh6X3XK_1lHBIBCR.LeGMidbsWkaXI_u_) : getting started with `ggplot`
  - [Tuesday morning, 6/15/21](https://sewanee-edu.zoom.us/rec/share/eO76cDTtYFDUTwb_Q9s70Fv56-afHNK19yM0UthQ8MbOcrRiqOKeC_M6U-8K7Cw.HTDoNfLadHxb9ZSu) : more with `ggplot` ; presentation by Pradip Malde and Stephen Alvarez on computational photography projects
  - [Tuesday afternoon, 6/15/21](https://sewanee-edu.zoom.us/rec/share/mDT87gB_I_lfvZsA9igxe7vGBTj4XFMHOgKCDyK36pXdlsNI6aYXwjZetSVBBImd.K1zIrbIVTaYxUkMK)
  - [Wednesday morning, 6/16/21](https://sewanee-edu.zoom.us/rec/share/cyXYf1ZVFH6XNu3sj4ZNOuu5INAuRTK5KQk1OiDeYdWs7yywLZG12i1P1It8u42s.bi6Jt0MToQBvCMRy)
  - [Wednesday afternoon, 6/16/21](https://sewanee-edu.zoom.us/rec/share/ObLatpxz_CZageSv9tO5v1eEwczBxySV5MG3sJ9Fj7z7Ynur2L6rIywKTltS5Y5j.4DTz3a4rTERosTcJ)
  - [Thursday morning, 6/17/21](https://sewanee-edu.zoom.us/rec/share/In141ssrJVgruKtqrhfZPPbxsO5n9aBLh5ANUXF_VuE6MEsI88jrC_u3SSkLqIbh.LnWVonNIXd-js8xZ) : presentation by Thrive Regional Partnership
  - [Thursday afternoon, 6/17/21](https://sewanee-edu.zoom.us/rec/share/oyiZzTG0Cjr9zCa7ykk7VsKrZHFRE24BrwpMl-xI4J2nkybwKaUobTnEa73Kf4U.myRMDz5JJTLKTQhV)
  - [Friday morning, 6/18/21](https://sewanee-edu.zoom.us/rec/share/6WDO9xjm3bZ-ugIzSSqt9QNuntuywvR-drU56zTuL9znOIJlbyN2O1PYfdy3oet9.axwasMcQgaMQnGuk) 
  - [Friday afternoon, 6/18/21](https://sewanee-edu.zoom.us/rec/share/HlbLBrsJvsZypHi6V_2Uyw_TSL52xAV0-GqIFgDfgN-_CDQ1rnLHpCO0cU5hE7ay.Htrrf1sX5mGZowRv)
  
### Week 3
  
  - [Monday morning, 6/21/21](https://sewanee-edu.zoom.us/rec/share/XSU1wqtaPk-9AUmQUJ_Y_EsRL8o3PabfjrT0PMBmmlhD4qJbOTxH66748m7Mof98.LkbeSfSi2WvtlpCe)
  - [Monday afternoon, 6/21/21](https://sewanee-edu.zoom.us/rec/share/a_9ijb688JuAqSe7Ntfc7vzuI1IBMA2eZ0rdpfoIE1qXMLoq_-aMQyYvqoykSlQl.7-hsjOWPDFoHRAK1)
  - [Tuesday morning, 6/22/21](https://sewanee-edu.zoom.us/rec/share/cDc7x2V6cu-3NJTk6U1RFJ5N82FCOgGqGlHwgv7h-IK12TC6d4p3GmmQXDAhGpNs.Pny4_d9AniOapvBJ)
  - [Tuesday afternoon, 6/22/21](https://sewanee-edu.zoom.us/rec/share/_BBatXlCAjop1o5G9cyacUg1vDz27MOtX3yrR1iIf5SH0SxrhM7CpTQymDJ8n8TA.vcS4SNF_A0ZsRqJG)
  - [Wednesday morning, 6/23/21](https://sewanee-edu.zoom.us/rec/share/RO_yUoEmrFnU9rz2ZE4sRV_vGaEVvy_61drlI3sRRZHFl1qAolo5L9w2wK0MVZLa.xUAj8mAR6-84VbmU)
  - [Wednesday afternoon, 6/23/21](https://sewanee-edu.zoom.us/rec/share/OU02zNEtVrvij22tcoHvmDRPV5EkxbjYIUlLVYTWXmsX12BFIX8Io_ExOL0DxSb7.6rJ2mjV7pPGOPwv0)
